2024-12-07 04:05:57,208 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 04:06:40,273 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 04:09:43,731 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 04:11:13,630 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 04:12:20,734 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 04:20:43,801 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 04:22:11,173 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 04:54:16,442 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 04:54:31,524 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 04:55:42,329 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 04:58:49,671 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 05:02:21,669 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 05:02:27,302 ERROR: Exception on /login [GET] [in /home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/app/routes.py", line 72, in login
    return render_template('login.html', title='Sign In', form=form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/lucas/microblog/app/templates/login.html", line 25, in template
    {% block content %}
jinja2.exceptions.TemplateAssertionError: block 'content' defined twice
2024-12-07 05:03:37,734 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 05:03:43,289 ERROR: Exception on /login [GET] [in /home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/app/routes.py", line 72, in login
    return render_template('login.html', title='Sign In', form=form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/lucas/microblog/app/templates/login.html", line 2, in top-level template code
    {% extends "base.html" %}
jinja2.exceptions.TemplateRuntimeError: extended multiple times
2024-12-07 05:05:36,448 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 05:19:28,137 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 05:23:01,025 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 05:34:24,504 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 05:39:47,604 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 05:46:58,978 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 05:49:50,667 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 05:52:43,781 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 05:56:16,741 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 05:57:50,426 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 06:00:44,990 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 06:10:37,761 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 06:12:15,530 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 06:14:13,811 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 06:20:07,814 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 06:29:40,118 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 06:32:06,708 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 06:33:59,415 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 06:41:35,895 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 06:48:44,621 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 06:50:53,766 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 06:51:44,597 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 06:52:51,700 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 06:56:38,391 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 06:57:20,161 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 07:02:00,489 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 07:02:48,685 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 07:05:09,611 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 07:06:10,510 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 07:07:26,337 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 07:07:26,337 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 07:07:26,337 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 07:07:26,342 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 20:55:01,711 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 20:55:30,501 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 20:56:03,606 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 20:59:47,149 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 21:08:23,966 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-07 21:08:26,352 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
